export enum CIROpcode {
  ASSIGN = 'ASSIGN',
  ALLOC = 'ALLOC',
  STORE = 'STORE',
  LOAD = 'LOAD',
  CALL = 'CALL',
  LABEL = 'LABEL',
  IF = 'IF',
  REL = 'REL',
  PHI = 'PHI',
  DEF = 'DEF',
  RET = 'RET',
  MATH = 'MATH',
  LEA = 'LEA',
  COMMENT = 'COMMENT',
}
